nginx:
  image: connorniu/nginx
  links:
      - node1:node1
      - node2:node2
      - node3:node3
  ports:
      - "80:80"
  volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - node:/src
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - node:/src
node3:
#    image: connorniu/node
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - node:/src

redis:
    image: redis
    ports:
        - "6379"